export const data = [
  {
    id: 1,
    nombre: "Pastel de Chocolate Deluxe",
    descripcion: "Pastel de chocolate con ganache y decorado con fresas.",
    precio: 250.0,
    imagen: "assets/Productos/pastel_chocolate.png",
  },
  {
    id: 2,
    nombre: "Cheesecake de Frutos Rojos",
    descripcion:
      "Tarta de queso con cobertura de frutos rojos y base de galleta.",
    precio: 285.0,
    imagen: "assets/Productos/cheesecake_frutos_rojos.png",
  },
  {
    id: 3,
    nombre: "Macarons Franceses",
    descripcion: "Caja de macarons de diferentes sabores y colores.",
    precio: 210.0,
    imagen: "assets/Productos/macarons_franceses.png",
  },
  {
    id: 4,
    nombre: "Cupcakes Vainilla y Caramelo",
    descripcion:
      "Cupcakes con buttercream de caramelo y decoraciones elegantes.",
    precio: 30.0,
    imagen: "assets/Productos/cupcakes_vainilla_caramelo.png",
  },
  {
    id: 5,
    nombre: "Brownies de Chocolate",
    descripcion:
      "Brownies esponjosos con trozos de nuez y cobertura de chocolate.",
    precio: 45.0,
    imagen: "assets/Productos/brownies_chocolate.png",
  },
  {
    id: 6,
    nombre: "Tarta de Manzana Artesanal",
    descripcion: "Tarta con manzanas caramelizadas y crujiente base de masa.",
    precio: 260.0,
    imagen: "assets/Productos/tarta_manzana.png",
  },
  {
    id: 7,
    nombre: "Galletas de Mantequilla Decoradas",
    descripcion: "Galletas artesanales decoradas con glaseado real.",
    precio: 50.0,
    imagen: "assets/Productos/galletas_mantequilla.png",
  },
  {
    id: 8,
    nombre: "Profiteroles con Chocolate",
    descripcion:
      "Profiteroles rellenos de crema pastelera y bañados en chocolate.",
    precio: 180.0,
    imagen: "assets/Productos/profiteroles_chocolate.png",
  },
  {
    id: 9,
    nombre: "Pastel Red Velvet",
    descripcion: "Pastel rojo aterciopelado con crema de queso.",
    precio: 320.0,
    imagen: "assets/Productos/pastel_red_velvet.png",
  },
  {
    id: 10,
    nombre: "Rollos de Canela",
    descripcion: "Rollos de canela con glaseado de vainilla y azúcar morena.",
    precio: 40.0,
    imagen: "assets/Productos/rollos_canela.png",
  },
  {
    id: 11,
    nombre: "Eclairs de Chocolate",
    descripcion: "Eclairs rellenos de crema y cubiertos con chocolate.",
    precio: 35.0,
    imagen: "assets/Productos/eclairs_chocolate.png",
  },
  {
    id: 12,
    nombre: "Bizcocho de Zanahoria",
    descripcion: "Bizcocho de zanahoria con crema de queso y nueces.",
    precio: 280.0,
    imagen: "assets/Productos/bizcocho_zanahoria.png",
  },
  {
    id: 13,
    nombre: "Tarta de Limón",
    descripcion: "Tarta con crema de limón y merengue tostado.",
    precio: 260.0,
    imagen: "assets/Productos/tarta_limon.png",
  },
  {
    id: 14,
    nombre: "Churros con Chocolate",
    descripcion: "Churros crujientes con azúcar y chocolate caliente.",
    precio: 60.0,
    imagen: "assets/Productos/churros_chocolate.png",
  },
  {
    id: 15,
    nombre: "Muffins de Arándanos",
    descripcion: "Muffins esponjosos con arándanos frescos y crumble.",
    precio: 75,
    imagen: "assets/Productos/muffins_arandanos.png",
  },
  {
    id: 16,
    nombre: "Pastel de Tres Leches",
    descripcion: "Pastel esponjoso bañado en leche condensada y crema.",
    precio: 170,
    imagen: "assets/Productos/pastel_tres_leches.png",
  },
  {
    id: 17,
    nombre: "Cannoli Italianos",
    descripcion: "Dulce crujiente relleno de ricotta y chispas de chocolate.",
    precio: 45,
    imagen: "assets/Productos/cannoli_italianos.png",
  },
  {
    id: 18,
    nombre: "Milhojas de Crema",
    descripcion: "Milhojas de hojaldre con crema pastelera y azúcar glas.",
    precio: 50,
    imagen: "assets/Productos/milhojas_crema.png",
  },
  {
    id: 19,
    nombre: "Tarta de Chocolate y Avellanas",
    descripcion: "Tarta con crema de avellanas y cobertura de chocolate.",
    precio: 180,
    imagen: "assets/Productos/tarta_chocolate_avellanas.png",
  },
  {
    id: 20,
    nombre: "Galletas con Chispas de Chocolate",
    descripcion: "Galletas caseras con chispas de chocolate y vainilla.",
    precio: 30,
    imagen: "assets/Productos/galletas_chocolate.png",
  },
];
